program ALLProj;

uses
  SysUtils,
  EZDSLBAr in 'Ezdslbar.pas',
  EZDSLBse in 'Ezdslbse.pas',
  EZDSLBtr in 'Ezdslbtr.pas',
  EZDSLCol in 'Ezdslcol.pas',
  EZDSLCts in 'Ezdslcts.pas',
  EZDSLDbl in 'Ezdsldbl.pas',
  EZDSLHsh in 'Ezdslhsh.pas',
  EZDSLLst in 'Ezdsllst.pas',
  EZDSLPQu in 'Ezdslpqu.pas',
  EZDSLQue in 'Ezdslque.pas',
  EZDSLSkp in 'Ezdslskp.pas',
  EZDSLStk in 'Ezdslstk.pas',
  EZDSLSup in 'Ezdslsup.pas',
  {$IFDEF Win32}
  EZDSLThd in 'Ezdslthd.pas',
  {$ENDIF}
  EZDSLRnd in 'Ezdslrnd.pas';


begin
end.
